name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.10.4
              otp: 21.3
          - pair:
              elixir: 1.14.0
              otp: 25.0.4
            lint: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get --only test

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check Dependencies
        run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile
        run: mix deps.compile

      - name: Test
        run: mix test
