name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            pair:
              elixir: '1.10.x'
              otp: '21.x'
          - os: ubuntu-22.04
            pair:
              elixir: '1.14.x'
              otp: '25.x'
            lint: lint
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Fetch Hex Cache
        uses: actions/cache@v3
        id: hex-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-

      - name: Install Dependencies
        run: mix deps.get --only test

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check Dependencies
        run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Test
        run: |
          mix compile --warnings-as-errors
          mix test
